apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-apache" (include "common.names.fullname" .)}}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: apache
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/apache2"
