apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-genie-pv
  labels:
    app: apache-genie-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/apache2"
