apiVersion: v1
kind: Service
metadata:
  name: genie
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - port: 8080
  type: ClusterIP
