apiVersion: apps/v1
kind: Deployment
metadata:
  name: genie-app
  labels:
    app: genie-app
spec:
  replicas: 1
  template:
    metadata:
      name: genie-app
      labels:
        app: genie-app
    spec:
      containers:
        - name: genie-app
          image: {{.Values.app.image.repository }}:{{.Values.app.image.tag}}
          imagePullPolicy: {{.Values.app.image.pullPolicy}}
      restartPolicy: Always
  selector:
    matchLabels:
      app: genie-app
