apiVersion: v1
kind: Service
metadata:
  name: genie-grpc
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - port: 9090
  type: ClusterIP
