apiVersion: batch/v1
kind: Job
metadata:
  name: genie-client-init
spec:
  template:
    spec:
      containers:
        - name: genie-client-init-job
          image: {{.Values.client.image.repository}}:{{.Values.client.image.tag}}
          imagePullPolicy: {{.Values.client.image.pullPolicy}}
          readinessProbe:
            httpGet:
              host: genie
              port: 8080
          command:
            - "python"
          args:
            - "init_demo.py"
      restartPolicy: Never

