apiVersion: v1
kind: Pod
metadata:
  name: presto
  labels:
    app: presto
spec:
  containers:
    - name: presto-demo-pod
      image: "starburstdata/presto:338-e.8"
---
apiVersion: v1
kind: Service
metadata:
  name: genie-presto
spec:
  selector:
    app: presto
  ports:
    - port: 8080
  type: ClusterIP



